name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (will be handled privately)
title: "[Security]: "
labels: ["security", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **IMPORTANT:** If this is a critical security vulnerability, please consider reporting it privately through GitHub's Security Advisory feature instead of creating a public issue.
        
        To report privately:
        1. Go to the repository's Security tab
        2. Click "Report a vulnerability"
        3. Fill out the private security advisory form
        
        Only use this public template for non-critical security concerns or if private reporting is not available.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Low - Minimal impact
        - Medium - Moderate impact
        - High - Significant impact
        - Critical - Severe impact requiring immediate attention
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the security vulnerability.
      placeholder: Describe the vulnerability...
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Code Injection
        - Cross-Site Scripting (XSS)
        - Data Exposure
        - Denial of Service
        - Insecure Dependencies
        - Insecure Storage
        - Path Traversal
        - Remote Code Execution
        - SQL Injection
        - Other
    validations:
      required: true

  - type: textarea
    id: affected-component
    attributes:
      label: Affected Component
      description: Which part of the extension is affected?
      placeholder: e.g., Connection profile management, SQL query execution, etc.
    validations:
      required: true

  - type: input
    id: affected-versions
    attributes:
      label: Affected Version(s)
      description: Which version(s) of the extension are affected?
      placeholder: e.g., 0.0.1, all versions, etc.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Who could be affected?
        - What data or systems are at risk?
        - What could an attacker do?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the vulnerability (if safe to share publicly).
      placeholder: |
        1. Configure extension with...
        2. Execute command...
        3. Observe vulnerability...
    validations:
      required: false

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: If applicable, provide a proof of concept (be careful not to include actual exploit code that could be misused).
      render: shell
    validations:
      required: false

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have suggestions for how to fix this vulnerability, please share them.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about the vulnerability.
    validations:
      required: false

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I will not publicly disclose details of this vulnerability until a fix is available
          required: true
        - label: I have not shared this vulnerability information with others
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
